=== UO288443/SEW/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="https://www.uniovi.es/" elementFormDefault="qualified" targetNamespace="https://www.uniovi.es/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre_circuito" />
				<xs:element ref="longitud_circuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha_carrera_2025" />
				<xs:element ref="hora_carrera_españa" />
				<xs:element ref="numero_vueltas" />
				<xs:element ref="localidad_proxima" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias_bibliograficas" />
				<xs:element ref="galeria_fotos" />
				<xs:element ref="galeria_videos" />
				<xs:element ref="origen_circuito" />
				<xs:element ref="puntos" />
				<xs:element ref="vencedor" />
				<xs:element ref="podio_2025" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre_circuito" type="xs:string" />
	<xs:element name="longitud_circuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:nonNegativeInteger">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:nonNegativeInteger">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha_carrera_2025" type="xs:date" />
	<xs:element name="hora_carrera_españa" type="xs:time" />
	<xs:element name="numero_vueltas" type="xs:nonNegativeInteger" />
	<xs:element name="localidad_proxima" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias_bibliograficas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="galeria_fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="galeria_videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="origen_circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:decimal" />
	<xs:element name="latitud" type="xs:decimal" />
	<xs:element name="altitud" type="xs:decimal" />
	<xs:element name="puntos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:nonNegativeInteger" />
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="tiempo" type="xs:duration"/>
	<xs:element name="podio_2025">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="nombre_piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre_piloto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="posicion" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="1" />
								<xs:enumeration value="2" />
								<xs:enumeration value="3" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== UO288443/SEW/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version='1.0' encoding='utf-8'?>
<circuito xmlns="https://www.uniovi.es/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.uniovi.es/ circuito.xsd"><nombre_circuito>Termas de Río Hondo</nombre_circuito>    
    <longitud_circuito unidades="m">4806</longitud_circuito>
    <anchura unidades="m">16</anchura>
    <fecha_carrera_2025>2025-03-16</fecha_carrera_2025>
    <hora_carrera_españa>18:00:00</hora_carrera_españa>
    <numero_vueltas>25</numero_vueltas>
    <localidad_proxima>Termas de Río Hondo, Santiago del Estero</localidad_proxima>
    <pais>Argentina</pais>
    <patrocinador>Michelin</patrocinador>
    <referencias_bibliograficas>
        <referencia>https://www.racingcircuits.info/south-america/argentina/autodromo-termas-de-rio-hondo.html</referencia>
        <referencia>https://en.wikipedia.org/wiki/Aut%C3%B3dromo_Termas_de_R%C3%ADo_Hondo</referencia>
        <referencia>https://autodromotermas.com/</referencia>
    </referencias_bibliograficas>
    <galeria_fotos>
        <foto>./multimedia/circuito.jpg</foto>
        <foto>./multimedia/vista_dron.jpg</foto>
    </galeria_fotos>
    <galeria_videos>
        <video>./multimedia/video.mp4</video>
    </galeria_videos>
    <origen_circuito>
        <coordenadas>
            <longitud>-27.510853113704</longitud>
            <latitud>-64.91983812515592</latitud>
            <altitud>263</altitud> 
        </coordenadas>
    </origen_circuito>
    <puntos>
  <punto>
    <distancia>000</distancia>
    <coordenadas>
      <longitud>-64.91983812515592</longitud>
      <latitud>-27.510853113704</latitud>
      <altitud>282.18</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>191</distancia>
    <coordenadas>
      <longitud>-64.92155964621332</longitud>
      <latitud>-27.51006982798949</latitud>
      <altitud>281.01</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>071</distancia>
    <coordenadas>
      <longitud>-64.92162949470273</longitud>
      <latitud>-27.50943847910297</latitud>
      <altitud>281.44</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>088</distancia>
    <coordenadas>
      <longitud>-64.92079253204619</longitud>
      <latitud>-27.50915987029514</latitud>
      <altitud>281.85</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>255</distancia>
    <coordenadas>
      <longitud>-64.91845931195053</longitud>
      <latitud>-27.51014281746643</latitud>
      <altitud>283.09</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>061</distancia>
    <coordenadas>
      <longitud>-64.91785488433564</longitud>
      <latitud>-27.51002459858692</latitud>
      <altitud>283.09</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>069</distancia>
    <coordenadas>
      <longitud>-64.9178264084283</longitud>
      <latitud>-27.50940513171758</latitud>
      <altitud>282.47</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>121</distancia>
    <coordenadas>
      <longitud>-64.91839777121366</longitud>
      <latitud>-27.50844541010273</latitud>
      <altitud>281.23</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>149</distancia>
    <coordenadas>
      <longitud>-64.91778933627489</longitud>
      <latitud>-27.50721531033114</latitud>
      <altitud>282.79</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>080</distancia>
    <coordenadas>
      <longitud>-64.91018664138286</longitud>
      <latitud>-27.50216244006998</latitud>
      <altitud>282.89</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>120</distancia>
    <coordenadas>
      <longitud>-64.90968218127391</longitud>
      <latitud>-27.50226978786477</latitud>
      <altitud>282.19</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>125</distancia>
    <coordenadas>
      <longitud>-64.90968790610451</longitud>
      <latitud>-27.50283848489583</latitud>
      <altitud>282.18</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>070</distancia>
    <coordenadas>
      <longitud>-64.91088521594035</longitud>
      <latitud>-27.50396582841161</latitud>
      <altitud>282.04</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>116</distancia>
    <coordenadas>
      <longitud>-64.91126375102654</longitud>
      <latitud>-27.50504591571635</latitud>
      <altitud>281.44</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>198</distancia>
    <coordenadas>
      <longitud>-64.90957332359486</longitud>
      <latitud>-27.50840597306539</latitud>
      <altitud>280.75</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>136</distancia>
    <coordenadas>
      <longitud>-64.90995562029859</longitud>
      <latitud>-27.50887436576985</latitud>
      <altitud>280.65</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>065</distancia>
    <coordenadas>
      <longitud>-64.91113879436895</longitud>
      <latitud>-27.50879018050259</latitud>
      <altitud>280.55</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>086</distancia>
    <coordenadas>
      <longitud>-64.9130170618525</longitud>
      <latitud>-27.50675628843302</latitud>
      <altitud>281.08</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>092</distancia>
    <coordenadas>
      <longitud>-64.91403948292111</longitud>
      <latitud>-27.50720264576438</latitud>
      <altitud>281.28</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>155</distancia>
    <coordenadas>
      <longitud>-64.91562699842854</longitud>
      <latitud>-27.50744428861476</latitud>
      <altitud>281.39</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>186</distancia>
    <coordenadas>
      <longitud>-64.91648098536569</longitud>
      <latitud>-27.50831106460077</latitud>
      <altitud>282.04</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>177</distancia>
    <coordenadas>
      <longitud>-64.91646103737112</longitud>
      <latitud>-27.50913018150951</latitud>
      <altitud>281.87</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>191</distancia>
    <coordenadas>
      <longitud>-64.91532685589605</longitud>
      <latitud>-27.51115265900524</latitud>
      <altitud>281.35</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>177</distancia>
    <coordenadas>
      <longitud>-64.91503841505897</longitud>
      <latitud>-27.51254041255841</latitud>
      <altitud>281.06</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>128</distancia>
    <coordenadas>
      <longitud>-64.915350446986</longitud>
      <latitud>-27.51295194695938</latitud>
      <altitud>281.02</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>135</distancia>
    <coordenadas>
      <longitud>-64.9158332393505</longitud>
      <latitud>-27.51266618563733</latitud>
      <altitud>281.02</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>195</distancia>
    <coordenadas>
      <longitud>-64.91614970636212</longitud>
      <latitud>-27.51195585461852</latitud>
      <altitud>281.60</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>181</distancia>
    <coordenadas>
      <longitud>-64.91967036891957</longitud>
      <latitud>-27.51088640604251</latitud>
      <altitud>281.64</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
  <punto>
    <distancia>076</distancia>
    <coordenadas>
      <longitud>-64.92140206</longitud>
      <latitud>-27.51075676</latitud>
      <altitud>281.29</altitud>
    </coordenadas>
    <sector>0</sector>
  </punto>
</puntos>



    <vencedor>
        <nombre>Marc Márquez</nombre>
        <tiempo>PT41M11.1S</tiempo>
    </vencedor>

    <podio_2025>
        <nombre_piloto posicion="1">Marc Márquez</nombre_piloto>
        <nombre_piloto posicion="2">Álex Márquez</nombre_piloto>
        <nombre_piloto posicion="3">Franco Morbidelli</nombre_piloto>
    </podio_2025>
</circuito>
